name: Build and Deploy
on:
  push:
    branches:
      - main
      - beta
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.4.0
      - name: Install and Build
        run: |
          npm ci --production=false # We also need to install dev dependencies for the build
          npm run build
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          NODE_ENV: production
      - name: Create archive as a preparation for the release
        run: zip -r release.zip dist/**
      - name: Release to GitHub
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy ğŸš€
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: dist
          git-config-name: Carsten Hoffmann
          git-config-email: carsten.c.hoffmann@deutschebahn.com
