name: Build and Deploy
on:
  push:
    branches:
      - deploy # TODO change this to main once this is tested
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          npm ci --production=false # We also need to install dev dependencies for the build
          npm run build
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          NODE_ENV: production
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
          git-config-name: Morl99
          git-config-email: carsten.c.hoffmann@deutschebahn.com
          single-commit: true
